### ISSUE TITLE
composite demo uses excess memory when using multi-GPU setup

### ISSUE THREAD

**Issue by Hisma** [THUDM/CogVLM#281]
### System Info / 系統信息

I am trying to run the composite demo using 2x 3090.  
I run the command `streamlit run main.py`.  It is able to load the model, but then it appears to try to load the model again and run out of memory.
Here is my client.py file showing only sections I modified.  I only load ('THUDM/cogagent-chat-hf'), and I add a parameter  `device_map="auto"` when loading the model, so that it properly splits the model across the 2 GPUs.

```python
# if you use all of Our model, include cogagent-chat cogvlm-chat cogvlm-grounding and put it in different devices, you can do like this.
models_info = {
    'tokenizer': {
        'path': os.environ.get('TOKENIZER_PATH', 'lmsys/vicuna-7b-v1.5'),
    },
    'agent_chat': {
        'path': os.environ.get('MODEL_PATH_AGENT_CHAT', 'THUDM/cogagent-chat-hf'),
        'device': ['cuda:0']
    },
}
...
    def __init__(self, models_info):
        self.models = {}
        self.tokenizer = AutoTokenizer.from_pretrained(models_info['tokenizer']['path'], trust_remote_code=True)
        for model_name, model_info in models_info.items():
            if model_name != 'tokenizer':
                self.models[model_name] = []
                for device in model_info['device']:
                    model = AutoModelForCausalLM.from_pretrained(
                        model_info['path'],
                        torch_dtype=torch_type,
                        device_map="auto",
                        low_cpu_mem_usage=True,
                        trust_remote_code=True,
                    ).to(device).eval()
                    self.models[model_name].append(model)
```

when loading the model, I add the additional parameter ` device_map="auto",` in model = `AutoModelForCausalLM.from_pretrained(` as you can see above, which allows the model to be split across multiple GPUs automatically.

But when I do this, I run out of GPU memory.  It loads the model and gets through its checkpoints, but then it's almost as though it tries to load the model again a second time.

### Who can help? / 谁可以帮助到您？

I can load 'THUDM/cogagent-chat-hf' just fine using the cli, as well as the openai api demo in my 48GB of VRAM provided by the 2x 3090.

Here is the code I use for the loading the model in the openai api demo, as an example - 
```python
if 'cuda' in DEVICE:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_PATH,
            trust_remote_code=True,
            torch_dtype=torch_type,
            low_cpu_mem_usage=True,
            device_map="auto"
        ).eval()
```
Adding `device_map="auto"` takes care of the GPU splitting automatically, and it fits in the 48GB of VRAM.

So there is some sort of bug in the composite_demo code that is causing excess memory to be used when using multi-GPU configuration.  

If you have a demo set-up with 2x3090, please try testing for yourself.  

Just add the parameter `device_map="auto"` when loading the model as I have shown in my code.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

run the run the composite demo using 2x 3090 by the command `streamlit run main.py`, with a modified `client.py` file to load only 'THUDM/cogagent-chat-hf', and adding the argument `device_map="auto"` when loading the model.

As explained above, `device_map="auto"` enables the openai api demo and cli demo to load just fine in 48GB of VRAM.  But the composite demo runs out of memory, as it appears to be trying to load the model a second time.

### Expected behavior / 期待表现

The model should be able to fit in 2 x 3090.

**Comment by darkacorn** [comment]
+1 can firm the issue - loads fine on single a6000 with that setup however wont split over smaller cards

**Comment by darkacorn** [comment]
@wenyihong can you explain why it wont split with auto over 2 3090 but it works fine in 1 a6000 
any other demo does split - compound does not

**Comment by zRzRzRzRzRzRzR** [comment]
in this script, every device will load a complete model not automatically assigned models
This means that you need to ensure that each card can accommodate the complete model. The design significance of this script is to implement parallel inference on multiple cards and allocate the problem to the idle graphics card.

**Comment by RandomInternetPreson** [comment]
Hello, I don't know if you are still looking for a solution but I have one:

In the cli_demo_hf.py code make the following changes:

1. add "import os" to the top of the code
2. Comment out and change 

![image](https://github.com/THUDM/CogVLM/assets/6488699/0da8d84b-0cae-459f-821f-2cf33eb9e432)


You'll get some errors, something about "pip install apex"  ¯\_(ツ)_/¯ Idk the model continued to load still without doing this.

Additionally, you'll see this: some weights of CogAgentForCausalLM were not initialized from the model checkpoint at CogVLM/cogagent-chat-hf/ and are newly initialized: ['model.cross_vision.vit.model.blocks.0.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_cos', etc.

I'm pretty sure this is because the model is prevented from being loaded twice, as in your original observation.
