### ISSUE TITLE
Can CogVLM accept interleaved images and texts (multiple images) as input?

### ISSUE THREAD

**Issue by McCarrtney** [THUDM/CogVLM#93]

**Comment by 1049451037** [comment]
Technically supported. But we didn't train with multi-image cases. Maybe fine-tuning is needed.

**Comment by McCarrtney** [comment]
> Technically supported. But we didn't train with multi-image cases. Maybe fine-tuning is needed.

Thank you. How to input multiple images into to model? Is there any specific input format?

**Comment by 1049451037** [comment]
First, you need to insert `<EOI>` in your str to indicate an image to be inserted in text:

https://github.com/THUDM/CogVLM/blob/3c254565408e180207de8a0b69f20473ecd5c157/utils/language.py#L48-L49

Then, you need to modify the `word_embedding_forward` to correctly insert image embeddings into text embeddings:

https://github.com/THUDM/CogVLM/blob/3c254565408e180207de8a0b69f20473ecd5c157/models/cogvlm_model.py#L84-L91

**Comment by rfan-debug** [comment]
@McCarrtney My trick is to let CogVLM to summarize the first image, and put the first image's summary together with the second image to chat about both images. It is a bit odd tho, but can work well in my use cases. A downside of this approach is that the current language model of CogVLM cannot understand a large context very well (due to its model size) so you might want to keep the size of summary of the first image small.

**Comment by 1049451037** [comment]
Yeah, that's a workaround.
